### ISSUE TITLE
NotesTakenDuringCreation.txt is missing

### ISSUE THREAD

**Issue by CM333** [TorchTheDragon/FNFTorchEdition#5]
I decided I'd take a look at NotesTakenDuringCreation.txt but I can't find it. It'd be really cool if it was there.

**Comment by TorchTheDragon** [comment]
It is located in the folder called "notes"
Direct Link to the text document: [NotesTakenDuringCreation.txt](https://github.com/TorchTheDragon/FNFTorchEdition/blob/main/notes/NotesTakenDuringCreation.txt)

Direct Link to Notes Folder: [notes](https://github.com/TorchTheDragon/FNFTorchEdition/tree/main/notes)

**Comment by CM333** [comment]
Thanks!

**Comment by TorchTheDragon** [comment]
Wait, you were talking about making your own engine on my Gamebanana tutorial page right? If so I recommend actually looking at these notes [AceCharactersSelectionNotes.txt](https://github.com/TorchTheDragon/FNFTorchEdition/blob/main/notes/AceCharacterSelectionNotes.txt). I recommend this because this character menu, which I have yet to make a tutorial on, because it works and looks a lot better than the previous one.
